### ISSUE TITLE
Add mTLS authN to direct connections

### ISSUE THREAD

**Issue by rhauch** [confluentinc/ide-sidecar#125]
Continuation of #96, #122, #123 and #124, and followup to #116 that added initial and limited direct connections (with GraphQL support) but did not support credentials and only worked with Kafka clusters and SR clusters that did not require authN.

We want to add mTLS support to direct connections (similar to basic creds) via the `kafka_cluster` and `schema_registry` definitions, and use this to connect to downstream resources (e.g., Kafka REST API, SR API endpoints, and Message Consumer API). All secrets in credentials will be write-only: the Connection REST API endpoints must always mask secrets. 

We'll track adding support for other credential types in separate issues:
* basic authN (#124)
* mTLS authN (this issue)
* OAuth authN (#126)
* Kerberos authN, or SSL/GSSAPI (#127)

**Comment by rohitsanj** [comment]
Already created https://github.com/confluentinc/ide-sidecar/issues/237. Re-closing this. :homer-disappear:
