### ISSUE TITLE
Clear cluster cache on connection update events

### ISSUE THREAD

**Issue by rohitsanj** [confluentinc/ide-sidecar#142]
Currently, when the SR URI of a local connection is updated to a new value, the sidecar continues to use the old value due to the cluster cache having stale information. 

The [`onConnectionUpdated` event handler method](https://github.com/confluentinc/ide-sidecar/blob/0d355a0334e0d525968faf2960a512a9b73f9da1/src/main/java/io/confluent/idesidecar/restapi/cache/ClusterCache.java#L192-L194) needs to include logic to clear all cached clusters for this connection, similar to what we do in the [`onConnectionDeleted` event listener method](https://github.com/confluentinc/ide-sidecar/blob/0d355a0334e0d525968faf2960a512a9b73f9da1/src/main/java/io/confluent/idesidecar/restapi/cache/ClusterCache.java#L211-L212). 

Simply clearing the cluster cache would do the trick by forcing future Kafka/SR REST proxy requests to fetch and re-cache any new cluster details.

This will need an associated test as well to prevent regressions.

**Comment by Cerchie** [comment]
addressed here https://github.com/confluentinc/ide-sidecar/pull/150
