### ISSUE TITLE
Cache schema fetch errors by connection ID, SR cluster ID and schema ID

### ISSUE THREAD

**Issue by rohitsanj** [confluentinc/ide-sidecar#153]
From https://github.com/confluentinc/ide-sidecar/pull/150/files#r1834988784:

> The NativeConsumeStrategy [reuses the same RecordDeserializer instance in every SimpleConsumer object it creates](https://github.com/confluentinc/ide-sidecar/blob/75ee1d1f4fb42754f8ab2c5db8abf99a29085fc8/src/main/java/io/confluent/idesidecar/restapi/messageviewer/strategy/NativeConsumeStrategy.java#L52-L56), and the RecordDeserialzer is caching error messages by schema ID regardless of the SR cluster. [..] we should cache the error messages by connection ID, SR cluster ID, and schema ID. This may be simpler, and this method could clear the error cache by connection ID.

**Comment by Cerchie** [comment]
This has been partially addressed by https://github.com/confluentinc/ide-sidecar/pull/150, however, in the process, an opportunity to refactor and create a schemaErrors class with read/write/clear methods was discovered. 

This way, the RecordDeserializer can use the supplied cache in schemaErrors, still keyed by Schema ID, and multiple MessageViewerClusterInfoProcessor(s) could find and reuse the same cache instances. 

Pull #158 set the stage for this change.

**Comment by Cerchie** [comment]
completed after follow up PR #200
