### ISSUE TITLE
Check connection statuses asynchronously

### ISSUE THREAD

**Issue by flippingbits** [confluentinc/ide-sidecar#181]
## Status Quo

At the moment, the endpoints `GET /gateway/v1/connections` and `GET /gateway/v1/connections/:id` (implicitly) call [DirectConnectionState#getConnectionStatus()](https://github.com/confluentinc/ide-sidecar/blob/main/src/main/java/io/confluent/idesidecar/restapi/connections/DirectConnectionState.java#L117), which synchronously checks the status of the connection. This can become problematic and lead to high request execution times, at least for the endpoint `GET /gateway/v1/connections` when users manage multiple direct connections.

## Proposal

We should migrate to asynchronously checking the statuses of connections in a background thread, similar to how we [refresh tokens of Confluent Cloud connections](https://github.com/confluentinc/ide-sidecar/blob/main/src/main/java/io/confluent/idesidecar/restapi/auth/RefreshCCloudTokensBean.java#L39). This would allow the endpoints `GET /gateway/v1/connections` and `GET /gateway/v1/connections/:id` to _instantly_ return the most recent status of each connection without having to interact with other/remote systems.

We should make the interval used for checking the connection statuses configurable. It probably makes sense to have one configuration property for each connection type. Initially, we can set the different intervals to the same value, e.g., 5 seconds.

The `status` field of Connections should expose when the status has been determined.

**Comment by rhauch** [comment]
#198 should make it easier to automatically keep the connections' status up-to-date.

**Comment by flippingbits** [comment]
Implemented by https://github.com/confluentinc/ide-sidecar/pull/199
