### ISSUE TITLE
Make settings related to SSL certificates configurable via API endpoint

### ISSUE THREAD

**Issue by flippingbits** [confluentinc/ide-sidecar#63]
A few users of [Confluent for VS Code](https://github.com/confluentinc/vscode) (https://github.com/confluentinc/vscode/issues/280 https://github.com/confluentinc/vscode/issues/268) reported that they ran into errors when working with Confluent Cloud and sitting behind a firewall that performs SSL inspection.

The sidecar should provide an API endpoint that allows the extension to pass the user's preferences on SSL certificates to the sidecar. Specifically, it should offer options to configure a custom CA cert and to disable verification of certs. The sidecar should respect the preferences and pass them to [instances of the Vert.x web client](https://github.com/confluentinc/ide-sidecar/blob/main/src/main/java/io/confluent/idesidecar/restapi/util/WebClientFactory.java). The sidecar should also provide an API endpoint to read the current preferences.

The endpoint for updating the preferences on the SSL certificates might look as follows:
```
PUT /gateway/v1/preferences

{
  "api_version": "gateway/v1",
  "kind": "Preferences",
  "spec": {
    "tls_pem_paths": ["/Users/stefan/rootca.pem"],
    "trust_all_certificates": false
  }
}
```

The field `tls_pem_paths` can be used to point the sidecar to one or multiple PEM files on the local file system of the user's machine. The field `trust_all_certificates` can be used to enable/disable verification of SSL certificates (if set to `true`, verification is enabled; if set to `false`, verification is disabled). If any of the fields is empty, the sidecar will fallback to the default behavior, which enforces verification of certificates in case of `trust_all_certificates` (i.e., it's set to `false`) and doesn't use a custom certificate in case of `tls_pem_paths`.

The endpoint for reading the current preferences might look as follows:
```
GET /gateway/v1/preferences

Content-Type: application/json
{
  "api_version": "gateway/v1",
  "kind": "Preferences",
  "metadata": {
    "self": "http://localhost:1234/gateway/v1/preferences"
  },
  "spec": {
    "tls_pem_paths": ["/Users/stefan/rootca.pem"],
    "trust_all_certificates": false
  },
  "status": {
    "example_status_field": true
  }
}
```

The field `status` is optional and will not be included if it is empty.

In the future, Confluent for VS Code might use these API endpoints to manage other user preferences, too.

**Comment by rhauch** [comment]
Thanks, @flippingbits. I think the `PUT` endpoint should take the same object, but with only `api_version`, `kind` and `spec` as required, and no fields (currently) required in the `spec` object. 

The `metadata` object is not required and would be ignored if provided. This makes it easier for the extension client to `GET` the current preferences, change the JSON from that response, and supply it as the payload for `PUT`.

The endpoint for updating the preferences on the SSL certificates would then look like:
```
PUT /gateway/v1/preferences

{
  "api_version": "gateway/v1",
  "kind": "Preferences",
  "spec": {
    "tls_pem_path": "/Users/stefan/rootca.pem",
    "trust_all_certificates": false
  }
}
```
By not requiring the `tls_pem_path` and `trust_all_certificates` fields, we are defining defaults (no PEM path, and trust-by-default). And, the following two requests would be equivalent and reset those fields to their defaults:
```
PUT /gateway/v1/preferences

{
  "api_version": "gateway/v1",
  "kind": "Preferences",
  "spec": {
    "tls_pem_path": null,
    "trust_all_certificates": true
  }
}
```
and
```
PUT /gateway/v1/preferences

{
  "api_version": "gateway/v1",
  "kind": "Preferences",
  "spec": {
  }
}
```
WDYT?

**Comment by rhauch** [comment]
> It's up for debate if users should be able to pass multiple paths as an array of strings to the option `tls_pem_path`.

If we think that's a possibility in the future, we might want to use an array of strings here, even if for now we enforce an array length of 0 or 1. We'd have to introduce a different field later if we want to keep backward compatibility, so it might be much easier to do it now.

**Comment by flippingbits** [comment]
> If we think that's a possibility in the future, we might want to use an array of strings here, even if for now we enforce an array length of 0 or 1. We'd have to introduce a different field later if we want to keep backward compatibility, so it might be much easier to do it now.

Good point! Let's call the preference `tls_pem_paths` and make it an array of strings.
